/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as FriendsRouteImport } from './routes/friends'
import { Route as SRouteImport } from './routes/s'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TabsRouteImport } from './routes/tabs'
import { Route as ESlugRouteImport } from './routes/e.$slug'
import { Route as TSlugIndexRouteImport } from './routes/t.$slug.index'
import { Route as TSlugBreakdownRouteImport } from './routes/t.$slug.breakdown'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRoute = FriendsRouteImport.update({
  id: '/friends',
  path: '/friends',
  getParentRoute: () => rootRouteImport,
} as any)
const SRoute = SRouteImport.update({
  id: '/s',
  path: '/s',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TabsRoute = TabsRouteImport.update({
  id: '/tabs',
  path: '/tabs',
  getParentRoute: () => rootRouteImport,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugIndexRoute = TSlugIndexRouteImport.update({
  id: '/t/$slug/',
  path: '/t/$slug/',
  getParentRoute: () => rootRouteImport,
} as any)
const TSlugBreakdownRoute = TSlugBreakdownRouteImport.update({
  id: '/t/$slug/breakdown',
  path: '/t/$slug/breakdown',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/expenses': typeof ExpensesRoute
  '/friends': typeof FriendsRoute
  '/s': typeof SRoute
  '/settings': typeof SettingsRoute
  '/tabs': typeof TabsRoute
  '/e/$slug': typeof ESlugRoute
  '/t/$slug/breakdown': typeof TSlugBreakdownRoute
  '/t/$slug/': typeof TSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/expenses': typeof ExpensesRoute
  '/friends': typeof FriendsRoute
  '/s': typeof SRoute
  '/settings': typeof SettingsRoute
  '/tabs': typeof TabsRoute
  '/e/$slug': typeof ESlugRoute
  '/t/$slug/breakdown': typeof TSlugBreakdownRoute
  '/t/$slug': typeof TSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/expenses': typeof ExpensesRoute
  '/friends': typeof FriendsRoute
  '/s': typeof SRoute
  '/settings': typeof SettingsRoute
  '/tabs': typeof TabsRoute
  '/e/$slug': typeof ESlugRoute
  '/t/$slug/breakdown': typeof TSlugBreakdownRoute
  '/t/$slug/': typeof TSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/expenses'
    | '/friends'
    | '/s'
    | '/settings'
    | '/tabs'
    | '/e/$slug'
    | '/t/$slug/breakdown'
    | '/t/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/expenses'
    | '/friends'
    | '/s'
    | '/settings'
    | '/tabs'
    | '/e/$slug'
    | '/t/$slug/breakdown'
    | '/t/$slug'
  id:
    | '__root__'
    | '/'
    | '/expenses'
    | '/friends'
    | '/s'
    | '/settings'
    | '/tabs'
    | '/e/$slug'
    | '/t/$slug/breakdown'
    | '/t/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExpensesRoute: typeof ExpensesRoute
  FriendsRoute: typeof FriendsRoute
  SRoute: typeof SRoute
  SettingsRoute: typeof SettingsRoute
  TabsRoute: typeof TabsRoute
  ESlugRoute: typeof ESlugRoute
  TSlugBreakdownRoute: typeof TSlugBreakdownRoute
  TSlugIndexRoute: typeof TSlugIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friends': {
      id: '/friends'
      path: '/friends'
      fullPath: '/friends'
      preLoaderRoute: typeof FriendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s': {
      id: '/s'
      path: '/s'
      fullPath: '/s'
      preLoaderRoute: typeof SRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabs': {
      id: '/tabs'
      path: '/tabs'
      fullPath: '/tabs'
      preLoaderRoute: typeof TabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug/': {
      id: '/t/$slug/'
      path: '/t/$slug'
      fullPath: '/t/$slug/'
      preLoaderRoute: typeof TSlugIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/t/$slug/breakdown': {
      id: '/t/$slug/breakdown'
      path: '/t/$slug/breakdown'
      fullPath: '/t/$slug/breakdown'
      preLoaderRoute: typeof TSlugBreakdownRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExpensesRoute: ExpensesRoute,
  FriendsRoute: FriendsRoute,
  SRoute: SRoute,
  SettingsRoute: SettingsRoute,
  TabsRoute: TabsRoute,
  ESlugRoute: ESlugRoute,
  TSlugBreakdownRoute: TSlugBreakdownRoute,
  TSlugIndexRoute: TSlugIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
